apiVersion: v2
appVersion: "17.6"
description: A Helm chart for PostgreSQL on Kubernetes
icon: https://www.postgresql.org/media/img/about/press/elephant64.png
keywords:
- database
- postgres
maintainers:
- name: groundhog2k
  url: https://github.com/groundhog2k/helm-charts
name: postgres
type: application
version: 1.5.8
