apiVersion: v2
appVersion: latest
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 15.x
description: Helm chart for Langflow IDE
maintainers:
- email: contact@langflow.org
  name: Langflow
name: langflow-ide
type: application
version: 0.1.1
