commonLabels:
  env: "production"
  billing-id: "12345"
  project: "langflow"
# selectorLabels is intentionally ignored by this chart.
# selectorLabels:
#   managed-by-custom: "true"

nameOverride: "langflow-service-b"
fullnameOverride: "langflow-service-b"

langflow:
  backend:
    env:
    - name: LANGFLOW_PORT
      value: '7860'
    - name: LANGFLOW_ALEMBIC_LOG_FILE
      value: /app/db/alembic.log
    - name: LANGFLOW_UPDATE_STARTER_PROJECTS
      value: 'false'
    - name: PHOENIX_API_KEY
      value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJBcGlLZXk6MSJ9.CGtAQeYTAr70Pk-cggfOvuZRgPg2v_jtHoilz-fwj3g
    - name: PHOENIX_COLLECTOR_ENDPOINT
      value: http://phoenix-a-svc.phoenix-dev.svc.cluster.local:6006
    - name: LANGFLOW_TRACING
      value: 'true'
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
    externalDatabase:
      database:
        value: langflow_db_b
      driver:
        value: postgresql
      enabled: true
      host:
        value: langflow-postgres-postgresql.langflow-dev.svc.cluster.local
      password:
        value: langflow-pass
      port:
        value: "5432"
      user:
        value: langflow
    sqlite:
      enabled: false
